### ISSUE TITLE
Route [mailcoach.emailLists.placeholders] not defined.

### ISSUE THREAD

**Issue by jmichaelterenin** [timmoh/mailcoach-custom-placeholder#1]
Are routes being loaded automatically, or does something have to be run that I've missed?
Laravel 6
PHP 7.4
MailCoach v2 Package

It didn't help to fix the file name, but noticed your routes filename is: mailcoach-custom-p**al**ceholder.php

**Comment by timmoh** [comment]
Add Route
File: `App\Providers\RouteServiceProvider`
```php
public function map() {
...
Route::mailcoachCustomPlaceholder($webPrefix);
//or
Route::mailcoachCustomPlaceholder('mailcoach');
...
}
```
