### ISSUE TITLE
Mailcoach 3.0+ middleware issue

### ISSUE THREAD

**Issue by Vardkin** [timmoh/mailcoach-custom-placeholder#2]
In Mailcoach 3.0+ an API was added. This changed the structure of the `middleware` array in the config file `config/mailcoach.php` (see [this commit](https://github.com/spatie/Mailcoach/commit/2b3730a1c6d528c3c708477a13c0b6449a69e5dd#diff-a535da1453605bc7dc4e62c1c9a4f175)) . 

Upon installation, mailcoach-custom-placeholder will throw the error `Illegal offset type in isset or empty` caused by not being able to resolve the proper middleware from `config(mailcoach.middelware)` in `MailcoachCustomPlaceholderServiceProvider.php` line 87.

## Expected Behavior
The `mailcoachCustomPlaceholder` macro should correctly resolve the respective middleware.

## Current Behavior
The fatal error `Illegal offset type in isset or empty` occurs when trying to load the `/mailcoach/email-lists/1/placeholders` endpoint.

## Possible Solution
If only web routes need to be resolved, change line 87 in `MailcoachCustomPlaceholderServiceProvider.php` to read:
```php
Route::middleware(config('mailcoach.middleware.web'))
```

## Steps to Reproduce
1. Install Mailcoach 3.0+ as a standalone application
2. Include this package and follow the installation steps.
3. Create an email list in the application.
4. navigate to `/mailcoach/email-lists/1/placeholders`

## Possible Implementation
The proposed solution above is only relevant if placeholders should not be available via the new Mailcoach API endpoints. I have not explored the API in much detail yet.
The above suggested change will probably be a breaking change to Mailcoach 2.+ compatibility. For this reason we should probably extract the logic for determining the Mailcoach middleware config into a new function.

**Comment by timmoh** [comment]
should be fixed in v3.0.0
@Vardkin does it work now?

**Comment by Vardkin** [comment]
Resolved in commit [4e34d521](https://github.com/timmoh/mailcoach-custom-placeholder/commit/4e34d521cb1018323ef7e15b6b9a213a1699cf58)
